### ISSUE TITLE
Grammatical error: where instead of were

### ISSUE THREAD

**Issue by MikeShepard** [devblackops/building-powershell-modules-feedback#10]
## Description
On page 105 you say about dependent modules that they "where already available" instead of "were already available" 

## Chapter/section/subsection

- Chapter: 
Dealing with Module Dependencies 
- Section:
4.1.5Installingdependencies
- Subsection:
in note about dependencies with title "Taking advantage of what is already available"
## Recommended fix

replace where with were.

**Comment by MikeShepard** [comment]
another one, in 5.3
Publish-Module has two parameters sets

should be parameter sets.

**Comment by devblackops** [comment]
Good catch. Thanks! 👍
