### ISSUE TITLE
Code Error: 

### ISSUE THREAD

**Issue by ryan-leap** [devblackops/building-powershell-modules-feedback#15]
## Description
Variables being referenced in the 'Exporting variables and alises from AcmeEmployee' code don't match the names of the variables as they are initially defined.  Specifically on line 2 and 3 these variables are defined:

$publicFunctionsPath
$privateFunctionsPath

But when referenced on lines 4 and 5 the variables are missing the 's' in Functions:

$publicFunctionPath
$privateFunctionPath

## Chapter/section/subsection
- Chapter: 7
- Section: 1
- Subsection: 3

## Screenshots

![image](https://user-images.githubusercontent.com/15367317/79175913-f2e33b80-7dcc-11ea-86c5-9214cbec068c.png)

**Comment by devblackops** [comment]
Thanks for catching that! Fixed.
