### ISSUE TITLE
Grammatical error: 5.1.3.3

### ISSUE THREAD

**Issue by Dev-Larks** [devblackops/building-powershell-modules-feedback#19]
## Description

Hi Brandon
Finished part 1 of the book today 

1) 5.1.3.3 Third-part NuGet Repositories (title)

2) Same section paragraph 2 - like advanced searching based on _tag_ that file share...

## Chapter/section/subsection

- Chapter: 5
- Section: 1
- Subsection: 3.2

## Recommended fix

1) Should be 'Third-party'?

2) Should be 'tags'?

**Comment by devblackops** [comment]
Thanks for catching that! 👍
