### ISSUE TITLE
Grammatical error: Capitalisation in table of contents.

### ISSUE THREAD

**Issue by Sup3rlativ3** [devblackops/building-powershell-modules-feedback#2]
## Description
There are multiple words that have been capitalised but aren't a name or the first word in a sentence. I could understand if this was a aesthetic choice but then there are other sentences that aren't conforming to that either.

I have ignored the part(chapter?) headings as well as the section headings. There is a lot that could be cleaned up here too.

## Chapter/section/subsection
Table of contents 
2,2.1, 7.4.1, 7.4.2, 8.2.1, 8.2.3, 8.2.4, 8.3.1, 8.3.2, 8.3.3, 8.4.2, 8.4.4, 9.5.2, 9.5.4, 9.5.5

## Recommended fix
2.1  "PowerShell version"
7.4.1 "Binary modules"
7.4.2 "Script modules"
8.2.1 "Finding modules online"
8.2.3 "Updating modules"
8.2.4 "Uninstalling modules"
8.3.1 "Listing installed modules"
8.3.2 "Getting module commands"
8.3.3 "Exploring a module"
8.4.2 "Manual installation"
8.4.4 "Saving modules"
9.5.2 "Trusting repositories"
9.5.4 "NuGet repositories"
9.5.5 "Filesystem repositories"

**Comment by devblackops** [comment]
Thanks for the feedback!

Yep, the section titles are inconsistent. Fixed 👍
