### ISSUE TITLE
Grammatical error: 

### ISSUE THREAD

**Issue by bchap1n** [devblackops/building-powershell-modules-feedback#20]
## Description
'to' is an unnecessary word here:

> For this example, you don’t need to create every
> function **to** that may be needed for a fully functioning module.

I think you mean to use the word 'Imagine' instead of 'Imaging':

> Imaging that
> in a real module, this may be a call to a HR system of some sort, where it then returns a valid
> employee ID that is not already is use.

## Chapter/section/subsection
9.3 - 'Creating a dot-sourced module'

**Comment by devblackops** [comment]
Thanks!
