### ISSUE TITLE
General feedback: 

### ISSUE THREAD

**Issue by Dev-Larks** [devblackops/building-powershell-modules-feedback#23]
## Description

Sorry Brandon if in the wrong spot but some feedback regarding section 9.4.1 Creating an project directory

When I was following this section today as I was reading in my current copy of the book the intended module structure diagram sits on the previous page when you move to the 9.4.2 Creating a build script section. In section 9.4.2.1 I think it would be helpful to state that the build script should be created in the C:/code/AcmeEmployee directory. I didn't initially capture this detail in the module structure image and while I could implicitly work out where it was created by the code listings in 9.4.3 I think it would be helpful to explicitly state the location where you create the build.ps1 file.

Thanks again for your continuing work on this book, I'm really enjoying the read and the clear explanations provided, it is a valuable contribution in the PowerShell community in my opinion.

Craig

**Comment by devblackops** [comment]
Thanks for the feedback. I'll try to make those sections clearer. I'm glad you're enjoying the book so far!
