### ISSUE TITLE
Grammatical error: You're instead of your

### ISSUE THREAD

**Issue by ianjohnson2000** [devblackops/building-powershell-modules-feedback#29]
## Description
In the working with the PATH environment variable section, in the paragraph above the supporting older versions information it says you're code instead of your code

## Chapter/section/subsection
11.13.1 Working with the PATH environment variable

- Chapter: 11
- Section: 13
- Subsection: 1

## Recommended fix
Change to your

**Comment by devblackops** [comment]
Thanks!
