### ISSUE TITLE
Grammatical error: to instead of too

### ISSUE THREAD

**Issue by Sup3rlativ3** [devblackops/building-powershell-modules-feedback#3]
## Description
You have used to instead of too. I'm sure this was just a typo rather than a deliberate choice.

## Chapter/section/subsection
3. Feedback

> Also, as PowerShell module practices evolve, so **to** will this book.

## Recommended fix
Change 'to' to 'too'
> Also, as PowerShell module practices evolve, so **too** will this book.

**Comment by devblackops** [comment]
Nice find. Thanks!
