### ISSUE TITLE
Grammatical error: Simple Typo in Build Script Section

### ISSUE THREAD

**Issue by thedavecarroll** [devblackops/building-powershell-modules-feedback#31]
## Description
In the following sentence, the highlighted `as` probably should be `and`.

"Now let’s walk through that this script does. First off, it’s using the [CmdletBinding()] attribute, as all scripts `as` functions should, so we get verbose, and debug output if we need it."

## Chapter/section/subsection

- Chapter: 9
- Section: 4
- Subsection: 2
- Subsubsection: 1

**Comment by devblackops** [comment]
Thanks @thedavecarroll  👍.

Fixed.
