### ISSUE TITLE
Code Error: Bonus chapter - Create a class using new-object

### ISSUE THREAD

**Issue by wsmelton** [devblackops/building-powershell-modules-feedback#32]
## Description
Minor syntax on the note block `Create a class using New-Object`.

## Chapter/section/subsection

- Chapter: PowerShell Classes Explained (bonus)
- Section: What is a PowerShell Class
- Subsection: Create a class using New-Object

## Current behavior
References `using the <type>]:::new() method`

## Expected behavior
Should be `<type>]::new()` (one less `:`)

## Possible solution
Remove the extra colon

## Screenshots

![image](https://user-images.githubusercontent.com/11204251/102030497-9def2f00-3d78-11eb-8619-8052018cb037.png)

**Comment by devblackops** [comment]
Thanks! Fixed.
