### ISSUE TITLE
Grammatical error: Typo in "Example bug report template"

### ISSUE THREAD

**Issue by TrisBits** [devblackops/building-powershell-modules-feedback#38]
## Description
In the "Example bug report template" it has as the following:

 assignees:  octopcat

## Chapter/section/subsection

- Chapter: 12
- Section: 6
- Subsection: 1

## Recommended fix

In the "Example bug report template" the correct value should be:

assignees:  octocat

**Comment by devblackops** [comment]
@TrisBits Thanks for catching that! Fixed.
