### ISSUE TITLE
Grammatical error:  Typo in 12.7

### ISSUE THREAD

**Issue by TrisBits** [devblackops/building-powershell-modules-feedback#39]
## Description
An incorrect word is present in the following sentence:

Imagine if you have a large GitHub project **will** multiple team members involved.

## Chapter/section/subsection

- Chapter: 12
- Section: 7
- Subsection:

## Recommended fix

The corrected sentence would be:

Imagine if you have a large GitHub project **with** multiple team members involved.

**Comment by devblackops** [comment]
Good catch! Fixed.
