### ISSUE TITLE
Code Error: CODEOWNERS Syntax

### ISSUE THREAD

**Issue by TrisBits** [devblackops/building-powershell-modules-feedback#40]
## Description
I could be wrong, as I am new to the syntax, but I believe the following parts are missing the @buildocat assignment.

14 *build*.ps1
15 psakefile.ps1

## Chapter/section/subsection

- Chapter: 12
- Section: 7
- Subsection: 1

## Possible solution

I believe the example should be:

14 *build*.ps1 @buildocat
15 psakefile.ps1 @buildocat

**Comment by devblackops** [comment]
Sharp eye. Fixed.

**Comment by TrisBits** [comment]
Thanks for the quick fixes!

I also wanted to say thank you for writing such an engaging and very helpful book.  One of the best PowerShell books I've ever come across.
