### ISSUE TITLE
Code Error: 

### ISSUE THREAD

**Issue by jbirley** [devblackops/building-powershell-modules-feedback#5]
Section:
2.3.2 Getting module commands
States:
If we only wanted to see aliases available from the appx module, we can tell Get-Command to do that using the -CommandType parameter.
List aliases exported from the appx module
Get-Command -Module appx -CommandType **Cmdlet**
Recommendation:
Get-Command -Module appx -CommandType **Alias**

**Comment by devblackops** [comment]
Thanks!
